version: 2

registries:
  pypi-python-org:
    type: python-index
    url: https://pypi.org/simple/
    replaces-base: true
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: "lockfile-only"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "all"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "deps"
      include: "scope"
    registries:
      - pypi-python-org 
    
  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ci-cd"
      - "dependencies"
    commit-message:
      prefix: "ci"
      include: "scope"
 
