site_name: ArchiPy
site_url: https://syntaxarc.github.io/ArchiPy/
site_description: Architecture + Python – Structured Development Simplified
site_author:  Hossein Nejati, Mehdi Einali
repo_url: https://github.com/SyntaxArc/ArchiPy
repo_name: SyntaxArc/ArchiPy
edit_uri: edit/master/docs/

# Copyright
copyright: Copyright &copy; 2025 Hossein Nejati, Mehdi Einali

# Theme configuration
theme:
  name: material
  language: en
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - content.code.copy
    - content.tabs.link
    - content.action.edit
  icon:
    repo: fontawesome/brands/github
  logo: assets/logo.jpg
  favicon: assets/logo.jpg

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SyntaxArc/ArchiPy
  version:
    provider: mike

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Plugins
plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [archipy]
          options:
            show_source: true
            show_root_toc_entry: true
            show_object_full_path: true
            heading_level: 2
            members_order: source
            docstring_style: google

# Navigation
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Features: features.md
  - Architecture: architecture.md
  - Contributing to Docs: contributing-docs.md
  - API Reference:
      - Overview: api_reference/index.md
      - Adapters: api_reference/adapters.md
      - Configs: api_reference/configs.md
      - Helpers: api_reference/helpers.md
      - Models: api_reference/models.md
      - Utils: api_reference/utils.md
  - Examples:
      - Config Management: examples/config_management.md
      - Adapters:
          - Overview: examples/adapters/index.md
          - Email: examples/adapters/email.md
          - Keycloak: examples/adapters/keycloak.md
          - MinIO: examples/adapters/minio.md
          - ORM: examples/adapters/postgres.md
          - Redis: examples/adapters/redis.md
      - Helpers:
          - Overview: examples/helpers/index.md
          - Decorators: examples/helpers/decorators.md
          - Interceptors: examples/helpers/interceptors.md
          - Metaclasses: examples/helpers/metaclasses.md
          - Utils: examples/helpers/utils.md
      - BDD Testing: examples/bdd_testing.md
  - Development: development.md
  - Contributing: contributing.md
  - Changelog: changelog.md
  - License: license.md
